### ISSUE TITLE
How to run it on windows..

### ISSUE THREAD

**Issue by timtruston** [Stouffi/typescript-react-starter#608]
I just cloned it onto a windows 10 machine. 
On powershell I ran "yarn", then "yarn start". Got the error "''TS_NODE_PROJECT' is not recognized as an internal or external command,' is not recognized as an internal or external command"

So I ran this command to add the variable to the environment:
`$Env:TS_NODE_PROJECT="webpack/tsconfig.json"`

I updated my package.json start script:

`"start": "webpack-dev-server --config webpack/webpack.dev.ts"`

Then ran "yarn start" again. Got the following error:

```
Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack: node_modules\webpack-dev-server\bin\webpack-dev-server.js
```

**Comment by I-keep-trying** [comment]
Exact same thing here. :-(
